name: ${artifactId}
version: ${project.version}
main: ${groupId}.${artifactId}
depend: [WorldEdit]
commands:
  races:
    description: Main command for Races plugin
    usage: Use /races help general to see help
  racessetup:
    description: Allows setting up of maps
    usage: Use /races help setup to see help
  racesconfirm:
    description: Confirms a command
    help: Use /races help confirm to see help
  racescancel:
    description: Cancels a command
    help: Use /races help confirm to see help
